# Generated by Django 5.2.7 on 2025-10-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('local_encontrado', models.CharField(blank=True, max_length=100, null=True)),
                ('data_encontrado', models.DateField()),
                ('status', models.CharField(choices=[('Em estoque', 'Em estoque'), ('Reivindicado', 'Reivindicado'), ('Devolvido', 'Devolvido')], default='Em estoque', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
