# Generated by Django 5.2.7 on 2025-11-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
