# Generated by Django 5.2.7 on 2025-11-22 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0002_item_aprovado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-data_encontrado', '-data_criacao']},
        ),
        migrations.CreateModel(
            name='Reivindicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_requerente', models.CharField(max_length=100)),
                ('contato', models.CharField(blank=True, help_text='Email, telefone ou matrícula', max_length=100, null=True)),
                ('detalhes', models.TextField(help_text='Detalhes que comprovem que o item é seu (sem ver a parte interna do item).')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Recusada', 'Recusada')], default='Pendente', max_length=20)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reivindicacoes', to='itens.item')),
            ],
            options={
                'ordering': ['-data_envio'],
            },
        ),
    ]
