# Generated by Django 5.2.7 on 2025-11-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0003_alter_item_options_reivindicacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reivindicacao',
            options={},
        ),
        migrations.AddField(
            model_name='reivindicacao',
            name='identificacao',
            field=models.CharField(blank=True, help_text='Ex.: matrícula, SIAPE, RG etc.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reivindicacao',
            name='vinculo',
            field=models.CharField(blank=True, choices=[('Estudante', 'Estudante'), ('Servidor', 'Servidor'), ('Terceirizado', 'Terceirizado'), ('Visitante', 'Visitante'), ('Outro', 'Outro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='aprovado',
            field=models.BooleanField(default=False, help_text='Se marcado, o item aparece na listagem pública.'),
        ),
        migrations.AlterField(
            model_name='reivindicacao',
            name='contato',
            field=models.CharField(blank=True, help_text='E-mail ou telefone para contato.', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='reivindicacao',
            name='detalhes',
            field=models.TextField(help_text='Detalhes que comprovam que o item é do requerente.'),
        ),
        migrations.AlterField(
            model_name='reivindicacao',
            name='nome_requerente',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='reivindicacao',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovada', 'Aprovada'), ('Recusada', 'Recusada')], default='Pendente', max_length=10),
        ),
    ]
